version: '3'
services:
  service_seller:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"